import type { BossMap } from "$lib/types";

export const bossHpMap: BossMap = {
    "Dark Mountain Predator": 50,
    "Destroyer Lucas": 50,
    "Leader Lugaru": 50,
    "Demon Beast Commander Valtan": 160,
    "Ravaged Tyrant of Beasts": 40,
    "Incubus Morphe": 60,
    "Nightmarish Morphe": 60,
    "Covetous Devourer Vykas": 160,
    "Covetous Legion Commander Vykas": 180,
    "Saydon": 160,
    "Kakul": 140,
    "Kakul-Saydon": 180,
    "Encore-Desiring Kakul-Saydon": 77,
    "Gehenna Helkasirs": 120,
    "Ashtarot": 170,
    "Primordial Nightmare": 190,
    "Brelshaza, Monarch of Nightmares": 200,
    "Imagined Primordial Nightmare": 20,
    "Pseudospace Primordial Nightmare": 20,
    "Phantom Legion Commander Brelshaza": 250,
    "Griefbringer Maurug": 150,
    "Evolved Maurug": 30,
    "Lord of Degradation Akkan": 190,
    "Plague Legion Commander Akkan": 220,
    "Lord of Kartheon Akkan": 300,
    "Tienis": 110,
    "Celestial Sentinel" : 60,
    "Prunya": 90,
    "Lauriel": 200,
    "Kaltaya, the Blooming Chaos": 120,
    "Rakathus, the Lurking Arrogance": 160,
    "Firehorn, Trampler of Earth": 160,
    "Lazaram, the Trailblazer": 200,
    "Killineza the Dark Worshipper": 180,
    "Valinak, Knight of Darkness": 180,
    "Valinak, Taboo Usurper": 180,
    "Valinak, Herald of the End": 180,
    "Thaemine the Lightqueller": 300,
    "Darkness Sword": 40,
    "Giant Darkness Sword": 40,
    "Darkness Legion Commander Thaemine": 350,
    // "tg41-Darkness Legion Commander Thaemine's Clone": 35,
    "Thaemine, Conqueror of Stars": 350,
};
