export const estherNameToIcon: Record<string, string> = {
  Thirain: "esther_0",
  Wei: "esther_1",
  Balthorr: "esther_2",
  Nineveh: "esther_3",
  Inanna: "esther_4",
  Azena: "esther_5",
  Shandi: "esther_6",
  "Kadan Attack": "esther_7",
  "Kadan Defense": "esther_8",
  Avele: "combined_3",
  Thar: "combined_2",
  Ephernia: "combined_4",
  Bastian: "combined_6",
  Ealyn: "combined_7",
  Jederico: "combined_8",
  Gustaven: "combined_9",
  Mystic: "combined_13",
  Mariu: "combined_14",
  Azakiel: "combined_15",
  Kharmine: "combined_17",
  Kadan: "esther_7",
  Armen: "combined_18",
  "Armen Attack": "combined_18",
  "Armen Defense": "combined_19"
};
