export const statType: Record<number, [string, boolean]> = {
  0: ["None", false],
  1: ["HP", false],
  2: ["MP", false],
  3: ["Strength", false],
  4: ["Dexterity", false],
  5: ["Intelligence", false],
  6: ["Vitality", false],
  15: ["Crit", false],
  16: ["Specialization", false],
  17: ["Domination", false],
  18: ["Swiftness", false],
  19: ["Endurance", false],
  20: ["Expertise", false],
  45: ["Evolution-Type Damage", true],
  46: ["Brand Power", true],
  47: ["Atk. Power", false],
  48: ["Bonus Damage", false],
  49: ["Atk. Power", true],
  50: ["Additional Damage", true],
  51: ["Atk. Power", true],
  52: ["Additional Damage", true],
  53: ["Skill Cooldown Decrease", true],
  54: ["Stagger Damage", true],
  74: ["Crit Rate", true],
  76: ["Crit Damage", true],
  77: ["Atk. Speed", false],
  78: ["Atk. Speed", true],
  79: ["Move Speed", false],
  80: ["Move Speed", true],
  104: ["Hyper Awakening Skill Damage", true],
  110: ["Awakening Skill Damage", true],
  123: ["Atk. Power", false],
  124: ["Atk. Power", false],
  141: ["Attack Power Sub 1", true],
  142: ["Attack Power Sub 2", true],
  147: ["Skill Damage Sub 1", true],
  148: ["Skill Damage Sub 2", true],
  150: ["Basic Atk. Power", true],
  151: ["Weapon Power", false],
  152: ["Weapon Power", true]
};
